var TechsByMA = {
    "ALMSCO33564 - ALAMOSA": [
        " ",
        "Brian Rowland",
        "Matthew Lobato",
        "Steve Montano",
    ],
    "ANCNMT33577 - ANACONDA": [
        " ",
        "Rusty Napier",
    ],
    "BASNWY33614 - BASIN": [
        " ",
        "Seth Edwards",
        "CJ Cooper",
        "Monte Hernandez",
    ],
    "BFLOWY00001 - BUFFALO":[
        " ",
        "Michael Huffman",
    ],
    "BGTMMT33578 - BIG TIMBER": [
        " ",
        "Kirk Stephens",
    ],
    "BLNGMT33579 - BILLINGS": [
        " ",
        "Andrew Cooper",
        "Brian Coles",
        "Deshaun Hogue",
        "Erik Freeman",
        "Justin Pluhar",
        "Kelly Braswell",
        "Michael Tiday",
        "Ryan Ralston",
        "Samuel White",
        "Robert Haskins",
    ],
    "BNVSCO33566 - BUENA VISTA": [
        " ",
        "Aaron Stewart",
        "Bradley Kavanagh",        
    ],
    "BUTTMT33581 - BUTTE": [
        " ",
        "Brock Hassler",
        "Don McLean",
        "Jeremy Walker",
        "Pete Nieves",
        "Ted Azure",        
    ],
    "BZMNMT33580 - BOZEMAN": [
        " ",
        "Blake Dailey",
        "Brian Bettle",
        "Michael Visscher",
        "Michael Westforth",
        "Neil Ross",
        "Rich Williams",        
    ],
    "CACYCO00038 - CANON CITY": [
        " ",
        "Donny Vela",
        "Matthew Reynolds",
        "Michael Goff",
        "Rory Randleman",
        
    ],
    "CHYNWY33610 - CHEYENNE": [
        " ",
        "Josh Sisk",
        "Joshua Brackett",
        "Stephen Helvig",
        "Steven Meinz",
        "Travis Burkett",        
    ],
    "CODYWY00008 - CODY": [
        " ",
        "Seth Edwards",
    ],
    "CRAGCO00041 - CRAIG": [
        " ",
        "Kendon Morgan",
    ],
    "CSPRWY33600 - CASPER": [
        " ",
        "Donnie Strange",
        "Eric Carlson",
        "Fabian Romero",
        "Gregory Schoonover",
        "Triston Garland",

    ],
    "CTBNMT33583 - CUT BANK": [
        " ",
        "Lucas Buehner",
    ],
    "DLLNMT33584 - DILLON": [
        " ",
        "Daniel Mehring",
    ],
    "DURNCO33605 - DURANGO": [
        " ",
        "Christopher Stephens",
        "Jesse Reeves",
        "Jon Reeves",

    ],
    "FTMRCO00045 - FORT MORGAN": [
        " ",
        "David Roseboom",
    ],
    "GDJTCO33606 - GRAND JUNCTION": [
        " ",
        "Christian Bruens",
        "Michael Labbitt",
        "Zachary Duarte",
        "Ismael Valencia",
        "Jacob Cadelinia",
        "Justin Capehart",
        "Mike Howerton",
        "Robert Marcus",
    ],
    "GLTTWY33570 - GILLETTE": [
        " ",
        "Ian Ross",
        "Joe Simmons",
        "Micheal Moore",
    ],
    "GRFLMT00018 - GREAT FALLS": [
        " ",
        "Brad Patera",
        "Daniel Lencioni",
        "Lucas Buehner",
        "Michael Atchison",
    ],
    "GUNNISON : GU": [
        " ",
        "Kevin Wolfe",
        "Matt Frey",
    ],
    "HAVRMT33588 - HAVRE": [
        " ",
        "Justin McClintic",
    ],
    "HLNAMT33589 - HELENA": [
        " ",
        "Justin Masiak",
        "Miles Gilbert",
        "Nathan Ratley",
        "Tyler Charlton",
    ],
    "HMTNMT00021 - HAMILTON": [
        " ",
        "Chris Koreski",
    ],
    "JCSNWY00013 - JACKSON": [
        " ",
        "Tim Lucht",
        "Erik Nelson",
        "Benn Regalado",
    ],
    "KLSLMT33594 - KALISPELL": [
        " ",
        "Bob Henry",
        "Brandon Bauer",
        "Jacob Gibbons",
        "John-Michael Wallace",
        "Michael Harrod",
    ],
    "LARMWY33571 - LARAMIE": [
        " ",
        "Jared Albrecht",
        "William Sample",
    ],
    "LDVLCO00049 - LEADVILLE": [
        " ",
        "Aaron Stewart",
        "Bradley Kavanagh",
    ],
    "LJNTCO33572 - LA JUNTA": [
        " ",
        "Adam Bickel",
        "Bryce Hiigel",
        "James Cordova",
    ],
    "LVTNMT33596 - LIVINGSTON": [
        " ",
        "Kirk Stephens",
    ],
    "MSSLMT00033 - MISSOULA": [
        " ",
        "Chris Koreski",
        "Daniel Bauer",
        "Arnold Ailer",
        "Billy Dean",
        "Bob Hughes",
        "Daniel Wilson",
        "Ryan Bulyca",
    ],
    "MTRSCO00054 - MONTROSE": [
        " ",
        "Andrew Casaday",
        "Dan Powers",
        "Kyle Henderson",
    ],
    "PLSNMT33598 - POLSON": [
        " ",
        "Mitchell Sampson",
    ],
    "RVTNWY33574 - RIVERTON": [
        " ",
        "Jonathan Marshall",
        "Jon Sonnenschein",
        "Michael Peterson",
    ],
    "RWLNWY00018 - RAWLINS": [
        " ",
        "Jake Henry",
    ],
    "SALDCO00058 - SALIDA": [
        " ",
        "Aaron Stewart",
        "Bradley Kavanagh",
    ],
    "SHRDWY00023 - SHERIDAN": [
        " ",
        "Jake Verhalen",
        "Nathan Barnes",
    ],
    "STNGCO00059 - STERLING": [
        " ",
        "Drew Swan",
    ],
    "TELLURIDE : TL": [
        " ",
        "Frank Gleason",
    ],
    "THRMWY00026 - THERMOPOLIS": [
        " ",
        "Jimmy Hill",
    ],
    "WLBGCO00061 - WALSENBURG": [
        " ",
        "Steve Montano",
    ],
    "WRLDWY33609 - WORLAND": [
        " ",
        "Monte Hernandez",
    ],
    "BAKROR11243 - BAKER CITY": [
        " ",
        "Andrew Young",
    ],
    "BRNSOR00020 - BURNS": [
        " ",
        "George Sekavec",
    ],
    "CLVLWA09386 - COLVILLE": [
        " ",
        "Jason Reeser",
    ],
    "COEUR D'ALENE : CD": [
        " ",
        "Clifford Lickfold",
        "Douglas Strinz",
        "John Hart",
        "Lee Thomas",
        "Michael Johnson",
    ],
    "COULEE DAM : EC": [
        " ",
        "Cody Fife",
    ],
    "CRCYCA21717 - CRESCENT CITY": [
        " ",
        "Austin Allen",
        "Bernardo Franco",
        "Chris Griffith",
        "Michael Pincombe",
        "Timothy Thompson",
    ],
    "CSBYOR09397 - COOS BAY": [
        " ",
        "Gonzalo Villa",
        "Lucas Hashberger",
        "Richard Hopkins",
        "Christopher Hubbard",
    ],
    "CTGVOR00012 - COTTAGE GROVE": [
        " ",
        "Brian Pierce",
        "Robert Cipolla",
        "Devon Davenport",
        "Elijah Laughlin",
        "Ethan Gould",
    ],
    "DLLSOR09537 - DALLAS": [
        " ",
        "Brandon Smith",
        "Chris Brooker",
    ],
    "ELBGWA20916 - ELLENSBURG": [
        " ",
        "Tony Garcia",
    ],
    "FLRNOR09230 - FLORENCE": [
        " ",
        "Brandon Moore",
    ],
    "GRPSOR25434 - GRANTS PASS": [
        " ",
        "Bryan Meier",
        "Michael McCarthy",
        "Richard Williams",
    ],
    "KLFLOR18645 - KLAMATH FALLS": [
        " ",
        "Bryan Powless",
        "Colby Hansen",
        "Shawn Paschal",
    ],
    "KNWCWA00023 - KENNEWICK": [
        " ",
        "Adam Ochoa",
        "Bryan Carrizales",
        "Erwin Felicitas",
        "Jacob Floyd",
        "Troy Roberts",
        "Carlos Barragan",
        "Jarrod Harrington",
        "Jason Aichele",
        "Jose Ramos",
        "Kevin McColloch",
        "Tyler Fordley",
        "Timothy Heffner",
    ],
    "LAGROR00007 - LA GRANDE": [
        " ",
        "Andrew Young",
        "Jeffrey Roy",
    ],
    "LKVWORAY10817 - LAKEVIEW": [
        " ",
        "Chris Samples",
        "Alaric Crandall",
    ],
    "LNCYOR09653 - LINCOLN CITY": [
        " ",
        "Kyle VanSeters",
        "Maarten Delanghe",
        "Jonathan Lee",
        "Norman Plough",
        "Christopher Nelson",
    ],
    "MDFDOR09952 - MEDFORD": [
        " ",
        "Michael McCarthy",
        "Richard Williams",
        "Aaron Weir",
        "Adam Zoll",
        "Chris Zakem",
        "Jaydee Husted",
        "Marcus James",
        "Morgan McDonald",
        "Timothy Heffner",
    ],
    "MOSCOW : MI": [
        " ",
        "Johnathan Holguin",
        "Jonathan Buttram",
        "Juan Torres",
    ],
    "OKANWA22922 - OMAK": [
        " ",
        "Cade Roy",
        "Shane Smith",
    ],
    "POST FALLS : PF": [
        " ",
        "Christopher Plummer",
        "Clifford Lickfold",
        "Lee Thomas",
        "Michael Johnson",
    ],
    "PULLMAN : PU": [
        " ",
        "Jonathan Buttram",
        "Juan Torres",
    ],
    "RSBGOR10333 - ROSEBURG": [
        " ",
        "Anthony Anderson",
        "Matt Morgan",
        "Jamie Pierce",
        "Zachary Bromagem",
    ],
    "SNSDWA21679 - SUNNYSIDE": [
        " ",
        "Joel Valdovinos",
        "Jose Arellano",
        "Jon Salme",
    ],
    "THDLOR08617 - THE DALLES": [
        " ",
        "Brandon McBride",
        "Josh Hegge",
    ],
    "TLMKOR09655 - TILLAMOOK": [
        " ",
        "Blake Guillory",
        "Devon Millang",
    ],
    "WLWLWA21798 - WALLA WALLA": [
        " ",
        "Clay DeBord",
        "Temby Zander",
        "Chandler Simpson",
        "Conner Baumann",
        "Travis Williams",
    ],
    "WNTCWA22557 - WENATCHEE": [
        " ",
        "Jake Christiansen",
        "John Visser",
        "Josh Fox",
        "Pete Freund",
        "Shawn Gustafson",
        "Ty Marshall",        
    ],
    "WRTNOR00004 - WARRENTON": [
        " ",
        "Elijah Solano",
        "Joshua Timko",
        "Tim Flaigg",        
    ],
    "YAKMWA11628 - YAKIMA": [
        " ",
        "Brandon Couchman",
        "Byron Robison",
        "Gregory Couette",
        "Jon Salme",
        "Robert Heide",        
    ],
    "ARSNCA21715 - ANDERSON": [
        " ",
        "Jacob Pniewski",
        "Ron Jennings",
        "Scott Donham",
        "Brett Fogarty",
        "Tony Bruccheri",
        "Jeff Hart",
        "Ryan Boss",
    ],
    "ATSCCA00082 - ATASCADERO": [
        " ",
        "Chad Gentry",
        "Jackson Price",
        "Jose Aguilar",
        "Mathew Evans",
    ],
    "BKFD01 - ARROW HEADEND": [
        " ",
        "Jesus Jaramillo",
        "Anthony Castro",
        "Carlos Serna",
        "Edgar Hernandez",
        "Heber Solares",
        "William Denson",
        "Alfredo Nieves",
        "Dale Cheeseman",
        "Saul Guzman",
        "Adrian Moerman",
        "Humberto Olvera",
    ],
    "BKFD02 - AUBURN HUB": [
        " ",
        "Jesus Jaramillo",
        "Carlos Serna",
        "Edgar Hernandez",
        "Heber Solares",
        "Alfredo Nieves",
        "Dale Cheeseman",

    ],
    "BKFD03 - FRUITVALE HUB": [
        " ",
        "Anthony Castro",
        "Edgar Hernandez",
        "Javier Alvarez",
        "German Bugarin",
        "Wilfredo Aranda",

    ],
    "BKFD04 - PANAMA HUB": [
        " ",
        "Abel Romero",
        "Felipe Pulido",
        "William Denson",
        "Saul Guzman",
    ],
    "BKFD05 - LAMONT HUB": [
        " ",
        "Arnold Gibson",
        "Alfredo Ruiz",
        "Matthew Gardello",
        "Adrian Moerman",
        "Humberto Olvera",        
    ],
    "BKFD06 - DELANO HUB": [
        " ",
        "Zachary Miller",
        "Joshua Villareal",        
    ],
    "BKFD06M - MCFARLAND HUB": [
        " ",
        "Zachary Miller",
        "Joshua Villareal",
    ],
    "BKFD07 - WASCO HUB": [
        " ",
        "German Bugarin",
        "Joshua Villareal",        
    ],
    "BKFD07S - SHAFTER HUB": [
        " ",
        "German Bugarin",
        "Joshua Villareal", 
    ],
    "BKFD08 - TAFT HUB": [
        " ",
        "Felipe Pulido",
        "William Denson",
    ],
    "BKFD09 - TEHACHAPI HUB": [
        " ",
        "Matthew Gardello",
    ],
    "CRCYNV33563 - CARSON CITY": [
        " ",
        "Brian Traver",
        "Cory Fowler",
        "Daniel Lawson",
        "David Husson",
    ],
    "ESCLCA00075 - ESCALON": [
        " ",
        "Albert Bocanegra",
        "Dar Singh",
        "Pablo Mendoza",
    ],
    "FLLNNV35146 - FALLON": [
        " ",
        "Dennis Coney",
        "Derrick Desomber",
    ],
    "GLRYCA17900 - GILROY": [
        " ",
        "Juan Garcia",
        "Manuel Galvan",
        "Ricardo Gomez",
        "Rick Hernandez",
        "Seth Smaltz",
    ],
    "GRDVNV30696 - GARDNERVILLE": [
        " ",
        "Howard Tande",
        "Jon Burrier",
        "Shawn White",
        "Tommy Nielsen",
    ],
    "GREENFIELD : GF": [
        " ",
        "Jacoby Mansfield",
        "Jose Ramirez",
    ],
    "HWTHNV0009 - HAWTHORNE": [
        " ",
        "Monte Walker",
    ],
    "PTVLCA19729 - PORTERVILLE": [
        " ",
        "Adelino Deniz",
        "Carlos Alanis",
        "Hernan Jaramillo",
        "Richard Newman",
        "Todd Osborn",
    ],
    "RENONV23981 - RENO": [
        " ",
        "Kyle Dalrymple",
        "Bob Barnett",
        "David Wood",
        "Gerardo Aguilar",
        "John Hammond",
        "Rene' Linares",
        "Richard Lujan",
        "AL Maestas",
        "Brian Spires",
        "Clif Stewart",
        "Jose Lepe",
        "Romeo Plata",
        "Troy Westgate",
        "Billy Douglas",
        "Donnie Sims",
        "John Wilson",
    ],
    "RENONV35142 - RENO": [
        " ",
        "Kyle Dalrymple",
        "Sean Cheek",
        "Jose Lepe",
        "Romeo Plata",
        "Troy Westgate",
        "Chris Callahan",
    ],
    "SNLOCA00480 - SAN LUIS OBISPO": [
        " ",
        "Jackson Price",
        "Jimmy Goodwin",
        "Ruben Carino",
        "Anthony Castro - SLO",
        "Edgar Hernandez",
        "Edgar Ramirez",
        "Gabriel Castro",
        "Roman Mercado",
    ],
    "STAHCA33562 - SOUTH LAKE TAHOE": [
        " ",
        "Kenny Allstead",
        "Salvador Uribe",
        "Shawn Miller",
        "Shawn Skog",
        "Steve Cooney",
    ],
    "SVSPNV30697 - SILVER SPRINGS": [
        " ",
        "Chris Ridge",
        "Derrick Desomber",
        "Monte Walker",
    ],
    "TRLCCA22463 - TURLOCK": [
        " ",
        "Arnold Velazquez",
        "Balentin Vasquez",
        "Carlos Aceves",
        "Pablo Mendoza",
        "Paulo Silveira",
        "Raynaldo Martinez",
    ],
    "WTVLCA00073 - WATSONVILLE": [
        " ",
        "Efrain Carrasco",
        "Jose Ramirez",
        "Luis Manzo",
        "Mario Serrano",
        "Sean Wienand",
    ],
    "YERINGTON-NV": [
        " ",
        "Monte Walker",
    ],


}