var TechsByHub = {
    "ALMSCO33564 - ALAMOSA": ["brian.r.rowland@charter.com;matthew.lobato@charter.com;steve.montano@charter.com;frank.valdez@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "ANCNMT33577 - ANACONDA": ["rusty.napier@charter.com;"],
    "BASNWY33614 - BASIN": ["seth.edwards@charter.com;cj.cooper@charter.com;monte.hernandez@charter.com"],
    "BFLOWY00001 - BUFFALO":["michael.huffman@charter.com;"],
    "BGTMMT33578 - BIG TIMBER": ["kirk.stephens@charter.com"],
    "BLNGMT33579 - BILLINGS": ["Andrew.Cooper@charter.com;Brian.Coles@charter.com;Deshaun.Hogue@charter.com;Erik.Freeman@charter.com;Erik.Freeman@charter.com;Justin.Pluhar@charter.com;Kelly.Braswell@charter.com;Michael.Tiday@charter.com;Ryan.Ralston@charter.com;Samuel.White@charter.com;Robert.Haskins@charter.com;"],
    "BNVSCO33566 - BUENA VISTA": ["Aaron.Stewart@charter.com;Bradley.Kavanagh@charter.com;"],
    "BUTTMT33581 - BUTTE": ["Brock.Hassler@charter.com;Jeremy.Walker@charter.com;pete.Nieves@charter.com;Ted.Azure@charter.com;robin.bagley@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "BZMNMT33580 - BOZEMAN": ["Blake.Dailey@charter.com;Brian.Bettle@charter.com;Michael.Visscher@charter.com;Michael.Westforth@charter.com;Neil.Ross@charter.com;richard.williams2@charter.com;robin.bagley@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "CACYCO00038 - CANON CITY": ["Donny.Vela@charter.com;matthew.reynolds@charter.com;michael.goff@charter.com;Rory.Randleman@charter.com;christopher.estey@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "CHYNWY33610 - CHEYENNE": ["Josh.Sisk@charter.com;Joshua.Brackett@charter.com;Stephen.Helvig@charter.com;Steven.Meinz@charter.com;Travis.Burkett@charter.com;russell.loetscher@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "CODYWY00008 - CODY": ["Seth.Edwards@charter.com;lee.millsap@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "CRAGCO00041 - CRAIG": ["Kendon.Morgan@charter.com;john.denney@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "CSPRWY33600 - CASPER": ["donnie.strange@charter.com;Eric.Carlson@charter.com;Fabian.Romero@charter.com;Gregory.Schoonover@charter.com;Triston.Garland@charter.com;michael.wolfe@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "CTBNMT33583 - CUT BANK": ["Lucas.Buehner@charter.com;ed.mcfadden@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "DLLNMT33584 - DILLON": ["Daniel.Mehring@charter.com;robin.bagley@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "DURNCO33605 - DURANGO": ["christopher.stephens@charter.com;Jesse.Reeves@charter.com;Jon.Reeves@charter.com;john.denney@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "FTMRCO00045 - FORT MORGAN": ["David.Roseboom@charter.com;russell.loetscher@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "GDJTCO33606 - GRAND JUNCTION": ["Christian.Bruens@charter.com;Michael.Labbitt@charter.com;Zachary.Duarte@charter.com;Ismael.G.Valencia@charter.com;Jacob.Cadelinia@charter.com;Justin.Capehart@charter.com;Mike.Howerton@charter.com;robert.marcus@charter.com;john.denney@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "GLTTWY33570 - GILLETTE": ["Ian.Ross@charter.com;Joe.Simmons@charter.com;Micheal.Moore@charter.com;michael.wolfe@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "GRFLMT00018 - GREAT FALLS": ["Brad.Patera@charter.com;Daniel.Lencioni@charter.com;Lucas.Buehner@charter.com;Michael.Atchison@charter.com;ed.mcfadden@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "GUNNISON : GU": ["Kevin.Wolfe@charter.com;Matt.Frey@charter.com;frank.valdez@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "HAVRMT33588 - HAVRE": ["Justin.McClintic@charter.com;ed.mcfadden@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "HLNAMT33589 - HELENA": ["Justin.Masiak@charter.com;Miles.Gilbert@charter.com;Nathan.Ratley@charter.com;Tyler.Charlton@charter.com;ed.mcfadden@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "HMTNMT00021 - HAMILTON": ["chris.Koreski@charter.com;raymond.roberts@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "JCSNWY00013 - JACKSON": ["Tim.Lucht@charter.com;Erik.Nelson@charter.com;Benn.Regalado@charter.com;lee.millsap@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "KLSLMT33594 - KALISPELL": ["bob.henry@charter.com;brandon.bauer@charter.com;Jacob.Gibbons@charter.com;John-Michael.Wallace@charter.com;Michael.Harrod@charter.com;raymond.roberts@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "LARMWY33571 - LARAMIE": ["Jared.Albrecht@charter.com;William.Sample@charter.com;russell.loetscher@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "LDVLCO00049 - LEADVILLE": ["Aaron.Stewart@charter.com;Bradley.Kavanagh@charter.com;frank.valdez@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "LJNTCO33572 - LA JUNTA": ["Adam.Bickel@charter.com;Bryce.Hiigel@charter.com;James.Cordova@charter.com;christopher.estey@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "LVTNMT33596 - LIVINGSTON": ["Kirk.Stephens@charter.com;robin.bagley@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "MSSLMT00033 - MISSOULA": ["chris.Koreski@charter.com;daniel.bauer@charter.com;Arnold.Ailer@charter.com;billy.dean@charter.com;Bob.Hughes2@charter.com;daniel.wilson@charter.com;Ryan.Bulyca@charter.com;raymond.roberts@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "MTRSCO00054 - MONTROSE": ["Andrew.Casaday@charter.com;dan.powers@charter.com;Kyle.Henderson@charter.com;thomas.obrien@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "PLSNMT33598 - POLSON": ["Mitchell.Sampson@charter.com;raymond.roberts@charter.com;todd.hawke@charter.com;bryan.riggs@charter.com;"],
    "RVTNWY33574 - RIVERTON": ["Jonathan.Marshall@charter.com;Jon.Sonnenschein@charter.com;Michael.A.Peterson@charter.com;lee.millsap@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "RWLNWY00018 - RAWLINS": ["Jake.Henry@charter.com;lee.millsap@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "SALDCO00058 - SALIDA": ["Aaron.Stewart@charter.com;Bradley.Kavanagh@charter.com;frank.valdez@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "SHRDWY00023 - SHERIDAN": ["Jake.Verhalen@charter.com;Nathan.Barnes@charter.com;michael.wolfe@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "STNGCO00059 - STERLING": ["Drew.Swan@charter.com;russell.loetscher@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "TELLURIDE : TL": ["Frank.Gleason@charter.com;thomas.obrien@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "THRMWY00026 - THERMOPOLIS": ["Jimmy.Hill2@charter.com;lee.millsap@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "WLBGCO00061 - WALSENBURG": ["Steve.Montano@charter.com;frank.valdez@charter.com;terry.fielder@charter.com;bryan.riggs@charter.com;"],
    "WRLDWY33609 - WORLAND": ["Monte.Hernandez@charter.com;lee.millsap@charter.com;dan.dorrell@charter.com;bryan.riggs@charter.com;"],
    "BAKROR11243 - BAKER CITY": ["andrew.p.young@charter.com;perry.smith@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "BRNSOR00020 - BURNS": ["George.Sekavec@charter.com;raymond.akesson@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "CLVLWA09386 - COLVILLE": ["Jason.Reeser@charter.com;david.sellers@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "COEUR D'ALENE : CD": ["Clifford.Lickfold@charter.com;Douglas.Strinz@charter.com;john.hart@charter.com;lee.thomas@charter.com;michael.johnson9@charter.com;david.sellers@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "COULEE DAM : EC": ["Cody.Fife@charter.com;eric.dye@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "CRCYCA21717 - CRESCENT CITY": ["austin.allen@charter.com;Bernardo.Franco@charter.com;Chris.Griffith@charter.com;michael.pincombe@charter.com;Timothy.Thompson@charter.com;christopher.bobince@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "CSBYOR09397 - COOS BAY": ["Gonzalo.Villa@charter.com;Lucas.Hashberger@charter.com;Richard.Hopkins@charter.com;christopher.hubbard@charter.com;timothy.schirmer@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "CTGVOR00012 - COTTAGE GROVE": ["Brian.Pierce@charter.com;robert.cipolla@charter.com;Devon.Davenport@charter.com;Elijah.Laughlin@charter.com;ethan.gould@charter.com;randy.weston@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "DLLSOR09537 - DALLAS": ["brandon.j.smith1@charter.com;Chris.Brooker@charter.com;albert.green@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "ELBGWA20916 - ELLENSBURG": ["tony.garcia@charter.com;mike.arola@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "FLRNOR09230 - FLORENCE": ["brandon.moore@charter.com;albert.green@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "GRPSOR25434 - GRANTS PASS": ["Bryan.Meier@charter.com;michael.mccarthy@charter.com;richard.williams2@charter.com;christopher.bobince@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "KLFLOR18645 - KLAMATH FALLS": ["Bryan.Powless@charter.com;Colby.Hansen@charter.com;Shawn.Paschal@charter.com;raymond.akesson@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "KNWCWA00023 - KENNEWICK": ["Adam.Ochoa@charter.com;Bryan.Carrizales@charter.com;Erwin.Felicitas@charter.com;Jacob.Floyd@charter.com;troy.roberts@charter.com;Carlos.BarraganZermeno@charter.com;Jarrod.Harrington@charter.com;Jason.Aichele@charter.com;Kevin.McColloch@charter.com;Tyler.Fordley@charter.com;Timothy.Heffner@charter.com;arnold.valencia@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "LAGROR00007 - LA GRANDE": ["andrew.p.young@charter.com;jeffrey.roy@charter.com;perry.smith@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "LKVWORAY10817 - LAKEVIEW": ["chris.samples@charter.com;alaric.crandall@charter.com;raymond.akesson@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "LNCYOR09653 - LINCOLN CITY": ["Kyle.VanSeters@charter.com;Maarten.Delanghe@charter.com;jonathan.lee@charter.com;Norman.Plough@charter.com;christopher.nelson@charter.com;albert.green@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "MDFDOR09952 - MEDFORD": ["michael.mccarthy@charter.com;richard.williams2@charter.com;Aaron.Weir@charter.com;Adam.Zoll@charter.com;Chris.Zakem@charter.com;Jaydee.Husted@charter.com;marcus.james@charter.com;Morgan.McDonald@charter.com;Timothy.Heffner@charter.com;christopher.bobince@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "MOSCOW : MI": ["Johnathan.Holguin@charter.com;Jonathan.Buttram@charter.com;juan.torres3@charter.com;david.sellers@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "OKANWA22922 - OMAK": ["Cade.Roy@charter.com;shane.smith@charter.com;eric.dye@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "POST FALLS : PF": ["Christopher.Plummer@charter.com;Clifford.Lickfold@charter.com;lee.thomas@charter.com;michael.johnson9@charter.com;david.sellers@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "PULLMAN : PU": ["Jonathan.Buttram@charter.com;juan.torres3@charter.com;david.sellers@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "RSBGOR10333 - ROSEBURG": ["anthony.anderson@charter.com;matt.morgan@charter.com;Jamie.Pierce@charter.com;Zachary.Bromagem@charter.com;timothy.schirmer@charter.com;ryan.gaither@charter.com;michael.smith3@charter.com;"],
    "SNSDWA21679 - SUNNYSIDE": ["Joel.Valdovinos@charter.com;Jose.Arellano@charter.com;Jon.Salme@charter.com;mike.arola@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "THDLOR08617 - THE DALLES": ["Brandon.McBride@charter.com;Josh.Hegge@charter.com;mike.arola@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "TLMKOR09655 - TILLAMOOK": ["Blake.Guillory@charter.com;Devon.Millang@charter.com;shawn.jayne@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "WLWLWA21798 - WALLA WALLA": ["Clay.DeBord@charter.com;Temby.Zander@charter.com;Chandler.Simpson@charter.com;Conner.Baumann@charter.com;travis.williams@charter.com;perry.smith@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "WNTCWA22557 - WENATCHEE": ["Jake.Christiansen@charter.com;john.visser@charter.com;Josh.Fox@charter.com;pete.freund@charter.com;Shawn.Gustafson@charter.com;ty.marshall@charter.com;eric.dye@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "WRTNOR00004 - WARRENTON": ["Elijah.Solano@charter.com;Joshua.Timko@charter.com;Tim.Flaigg@charter.com;shawn.jayne@charter.com;brent.sears@charter.com;michael.smith3@charter.com;"],
    "YAKMWA11628 - YAKIMA": ["Brandon.Couchman@charter.com;Byron.Robison@charter.com;Gregory.Couette@charter.com;Jon.Salme@charter.com;Robert.Heide@charter.com;mike.arola@charter.com;dave.myhre@charter.com;michael.smith3@charter.com;"],
    "ARSNCA21715 - ANDERSON": ["Jacob.Pniewski@charter.com;Ron.Jennings@charter.com;Scott.Donham@charter.com;Brett.Fogarty@charter.com;Tony.Bruccheri@charter.com;Jeffrey.Hart@charter.com;Ryan.Boss@charter.com;nikolos.goodman@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "ATSCCA00082 - ATASCADERO": ["Chad.Gentry@charter.com;Jackson.Price@charter.com;jose.aguilar@charter.com;Mathew.Evans@charter.com;nikolos.goodman@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "BKFD01 - ARROW HEADEND": ["Jesus.Jaramillo@charter.com;anthony.castro@charter.com;Carlos.Serna@charter.com;edgar.hernandez@charter.com;Heber.SolaresRamirez@charter.com;William.Denson@charter.com;Alfredo.Nieves@charter.com;Dale.Cheeseman@charter.com;Saul.Guzman@charter.com;Adrian.Moerman@charter.com;Humberto.Olvera@charter.com;gregory.eppler@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD02 - AUBURN HUB": ["Jesus.Jaramillo@charter.com;Carlos.Serna@charter.com;edgar.hernandez@charter.com;Heber.SolaresRamirez@charter.com;Alfredo.Nieves@charter.com;Dale.Cheeseman@charter.com;gregory.eppler@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD03 - FRUITVALE HUB": ["anthony.castro@charter.com;edgar.hernandez@charter.com;Javier.Alvarez@charter.com;German.Bugarin@charter.com;Wilfredo.Aranda@charter.com;nikolos.goodman@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "BKFD04 - PANAMA HUB": ["abel.romero@charter.com;Felipe.Pulido@charter.com;William.Denson@charter.com;Saul.Guzman@charter.com;john.marquez@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD05 - LAMONT HUB": ["Arnold.Gibson@charter.com;Alfredo.Ruiz@charter.com;Matthew.Gardello@charter.com;Adrian.Moerman@charter.com;Humberto.Olvera@charter.com;gregory.eppler@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD06 - DELANO HUB": ["zachary.miller@charter.com;Joshua.Villareal@charter.com;john.marquez@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD06M - MCFARLAND HUB": ["zachary.miller@charter.com;Joshua.Villareal@charter.com;john.marquez@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD07 - WASCO HUB": ["German.Bugarin@charter.com;Joshua.Villareal@charter.com;scott.obert@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD07S - SHAFTER HUB": ["German.Bugarin@charter.com;Joshua.Villareal@charter.com;scott.obert@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD08 - TAFT HUB": ["Felipe.Pulido@charter.com;William.Denson@charter.com;john.marquez@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "BKFD09 - TEHACHAPI HUB": ["Matthew.Gardello@charter.com;john.marquez@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "CRCYNV33563 - CARSON CITY": ["Brian.Traver@charter.com;Cory.Fowler@charter.com;Daniel.Lawson@charter.com;David.Husson@charter.com;thomas.robertson@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "ESCLCA00075 - ESCALON": ["Albert.Bocanegra@charter.com;dar.singh@charter.com;Pablo.Mendoza@charter.com;orlando.soliz@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "FLLNNV35146 - FALLON": ["Dennis.Coney@charter.com;brian.ramil@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "GLRYCA17900 - GILROY": ["juan.r.garcia@charter.com;Manuel.Galvan@charter.com;Ricardo.Gomez@charter.com;Rick.Hernandez@charter.com;Seth.Smaltz@charter.com;tyrone.sears@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "GRDVNV30696 - GARDNERVILLE": ["Howard.Tande@charter.com;Jon.Burrier@charter.com;shawn.white@charter.com;Tommy.Nielsen@charter.com;thomas.robertson@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "GREENFIELD : GF": ["Jacoby.Mansfield@charter.com;jose.ramirez@charter.com;tyrone.sears@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "HWTHNV0009 - HAWTHORNE": ["Monte.Walker@charter.com;brian.ramil@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "PTVLCA19729 - PORTERVILLE": ["Adelino.Deniz@charter.com;Carlos.Alanis@charter.com;Hernan.Jaramillo@charter.com;Richard.Newman@charter.com;Todd.Osborn@charter.com;gregory.eppler@charter.com;asencion.leal@charter.com;trentyn.roden@charter.com;"],
    "RENONV23981 - RENO": ["Kyle.Dalrymple@charter.com;Bob.Barnett@charter.com;David.Wood2@charter.com;Gerardo.Aguilar@charter.com;John.Hammond2@charter.com;Rene.Linares@charter.com;Richard.Lujan@charter.com;Al.Maestas@charter.com;Brian.Spires@charter.com;Clif.Stewart@charter.com;Jose.Lepe@charter.com;Romeo.Plata@charter.com;Troy.Westgate@charter.com;Billy.Douglas@charter.com;Donnie.Sims@charter.com;john.wilson@charter.com;john.boling@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "RENONV35142 - RENO": ["Kyle.Dalrymple@charter.com;Sean.Cheek@charter.com;Jose.Lepe@charter.com;Romeo.Plata@charter.com;Troy.Westgate@charter.com;Chris.Callahan@charter.com;john.boling@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "SNLOCA00480 - SAN LUIS OBISPO": ["Jackson.Price@charter.com;Jimmy.Goodwin@charter.com;Ruben.Carino@charter.com;anthony.castro@charter.com;edgar.hernandez@charter.com;edgar.ramirez@charter.com;gabriel.castro@charter.com;Roman.Mercado@charter.com;nikolos.goodman@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "STAHCA33562 - SOUTH LAKE TAHOE": ["kenny.allstead@charter.com;Salvador.Uribe@charter.com;shawn.miller@charter.com;Shawn.Skog@charter.com;Steve.Cooney@charter.com;john.boling@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "SVSPNV30697 - SILVER SPRINGS": ["Chris.Ridge@charter.com;Monte.Walker@charter.com;;brian.ramil@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
    "TRLCCA22463 - TURLOCK": ["Arnold.Velazquez@charter.com;Balentin.Vasquez@charter.com;Carlos.Aceves@charter.com;Pablo.Mendoza@charter.com;Paulo.Silveira@charter.com;Raynaldo.Martinez@charter.com;orlando.soliz@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "WTVLCA00073 - WATSONVILLE": ["Efrain.Carrasco@charter.com;jose.ramirez@charter.com;Luis.Manzo@charter.com;Mario.Serrano@charter.com;sean.wienand@charter.com;tyrone.sears@charter.com;anthony.ramirez@charter.com;trentyn.roden@charter.com;"],
    "YERINGTON-NV": ["Monte.Walker@charter.com;brian.ramil@charter.com;david.steger@charter.com;trentyn.roden@charter.com;"],
}